from typing import Protocol

from sqlalchemy.orm import Session


class PlanExecutionCollaborators(Protocol):
    def withdraw_warehouse_stock(self, session: Session, request): ...
    def withdraw_finished_plan_stock(self, session: Session, **kwargs): ...
    def accept_issued_inventory(self, session: Session, *args, **kwargs) -> None: ...
    def initialize_order_production(self, session: Session, order, **kwargs) -> None: ...


__all__ = ["PlanExecutionCollaborators"]
