from typing import Protocol

from sqlalchemy.orm import Session


class PlanExecutionCollaborators(Protocol):
    def withdraw_warehouse_stock(self, session: Session, request): ...
    def reserve_finished_plan_stock(self, session: Session, **kwargs) -> int: ...
    def release_finished_plan_stock(self, session: Session, production_plan_id: int) -> None: ...
    def accept_issued_inventory(self, session: Session, *args, **kwargs) -> None: ...
    def initialize_order_production(self, session: Session, order, **kwargs) -> None: ...
    def rollback_unstarted_order_production(self, session: Session, order) -> None: ...
    def ensure_order_has_no_shipments(self, session: Session, customer_order_id: int) -> None: ...
    def reverse_plan_warehouse_issues(self, session: Session, **kwargs) -> None: ...
    def ensure_no_completed_plan_storage(self, session: Session, **kwargs) -> None: ...


__all__ = ["PlanExecutionCollaborators"]
