from typing import Protocol

from sqlalchemy.orm import Session


class PlanExecutionCollaborators(Protocol):
    def withdraw_warehouse_stock(self, session: Session, request): ...
    def reserve_finished_plan_stock(self, session: Session, **kwargs) -> int: ...
    def release_finished_plan_stock(self, session: Session, production_plan_id: int) -> None: ...
    def accept_issued_inventory(self, session: Session, *args, **kwargs) -> None: ...
    def initialize_order_production(self, session: Session, order, **kwargs) -> None: ...


__all__ = ["PlanExecutionCollaborators"]
