/** Material color values used by canvas libraries that cannot read scoped CSS variables reliably. */
export const materialColors = {
  primary: '#415f91',
  primaryContainer: '#d6e3ff',
  secondary: '#565f71',
  secondaryContainer: '#dae2f9',
  tertiary: '#705575',
  tertiaryContainer: '#fad8fd',
  success: '#386a20',
  successContainer: '#d8f9c8',
  warning: '#825500',
  warningContainer: '#ffdea8',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  flowProduction: '#386a20',
  flowProductionContainer: '#d8f9c8',
  flowOutsource: '#6750a4',
  flowOutsourceContainer: '#eaddff',
  flowAssembly: '#00639a',
  flowAssemblyContainer: '#cce5ff',
  flowFinished: '#006a60',
  flowFinishedContainer: '#9ef2e4',
  flowQc: '#904a4f',
  flowQcContainer: '#ffdadb',
  outline: '#74777f',
  outlineVariant: '#c4c6d0',
  surfaceContainerLow: '#f3f3fa',
} as const
