WORK_ORDER_TAG = "tag"
WORK_ORDER_PURCHASE_RECEIPT = "purchase_receipt"
WORK_ORDER_ASSEMBLY = "assembly"

QC_SUPPORTED_WORK_ORDER_TYPES = frozenset({
    WORK_ORDER_TAG,
    WORK_ORDER_PURCHASE_RECEIPT,
    WORK_ORDER_ASSEMBLY,
})
REWORK_TRACKED_WORK_ORDER_TYPES = frozenset({
    WORK_ORDER_TAG,
    WORK_ORDER_ASSEMBLY,
})

MOVEMENT_QC_DISPATCH = "qc_dispatch"
