WORK_ORDER_STANDARD = "standard"
WORK_ORDER_PURCHASE_RECEIPT = "purchase_receipt"
WORK_ORDER_ASSEMBLY = "assembly"

QC_SUPPORTED_WORK_ORDER_TYPES = frozenset({
    WORK_ORDER_STANDARD,
    WORK_ORDER_PURCHASE_RECEIPT,
    WORK_ORDER_ASSEMBLY,
})
REWORK_TRACKED_WORK_ORDER_TYPES = frozenset({
    WORK_ORDER_STANDARD,
    WORK_ORDER_ASSEMBLY,
})
